#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */
enum custom_keycodes {
    WRITE = SAFE_RANGE,
    QUIT,
    ASSIGN,
};

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
    case WRITE:
        if (record->event.pressed) {
            SEND_STRING(SS_TAP(X_ESC) ":w" SS_TAP(X_ENT));
        } else {
            // when keycode QMKBEST is released
        }
        break;

    case QUIT:
        if (record->event.pressed) {
            SEND_STRING(SS_TAP(X_ESC) ":q" SS_TAP(X_ENT));
        } else {
            // when keycode QMKURL is released
        }
        break;

    case ASSIGN:
        if (record->event.pressed) {
           SEND_STRING("->"); // selects all and copies
        }
        break;
    }
    return true;
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_ortho_5x12(
            LGUI(KC_F), KC_TRNS, KC_LCBR, KC_LPRN, KC_LBRC, KC_TRNS, KC_TRNS, KC_RBRC, KC_RPRN, KC_RCBR, KC_TRNS, KC_DELETE,
            KC_TAB, KC_Q, KC_Y, KC_O, KC_U, KC_Z, KC_W, KC_D, KC_N, KC_C, KC_B, KC_F12,
            LSFT_T(KC_BSPC), KC_H, KC_I, KC_E, KC_A, KC_UNDS, KC_G, KC_T, KC_R, KC_S, KC_P, LSFT_T(KC_EQUAL),
            KC_LCTL, LT(1,KC_QUOT), LT(1,KC_COMM), KC_J, KC_K, KC_X, KC_V, KC_M, KC_L, KC_F, KC_SLSH, RCTL_T(KC_SCLN),
            KC_LGUI, KC_LCTL, KC_LSFT, KC_LALT, LT(2,KC_ESC), LT(3,KC_DOT), KC_SPC, LT(5,KC_ENT), KC_LEFT, KC_RGHT, KC_TRNS, TG(6)),
	[1] = LAYOUT_ortho_5x12(
            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, LGUI(LSFT(KC_F1)),LGUI(LSFT(KC_F2)),LGUI(LSFT(KC_F3)),LGUI(LSFT(KC_F4)), LGUI(LSFT(KC_F5)),
            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, LGUI(KC_W), LGUI(KC_D), LGUI(KC_UP), LGUI(KC_C), LGUI(KC_J), LGUI(LSFT(KC_F6)),
            KC_TRNS, KC_TRNS, LGUI(KC_I), LGUI(KC_E), LGUI(KC_A), KC_TRNS, LGUI(KC_G), LGUI(KC_LEFT), LGUI(KC_DOWN), LGUI(KC_RIGHT), LGUI(KC_P),  LGUI(LSFT(KC_F7)),
            KC_TRNS, KC_TRNS, KC_TRNS, RCTL(KC_J), RCTL(KC_K), LGUI(KC_X), LGUI(KC_V), LGUI(KC_1), LGUI(KC_2), LGUI(KC_3), LGUI(KC_4), LGUI(KC_5),
            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LSFT, LGUI(KC_SPC), LGUI(KC_ENTER), LGUI(KC_F1), LGUI(KC_F2), LGUI(KC_F3), KC_TRNS),
	[2] = LAYOUT_ortho_5x12(
            LALT(LSFT(KC_TAB)), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
            LALT(KC_TAB), QUIT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PGUP, KC_HOME, KC_UP, KC_END, KC_TRNS, KC_F10,
            LCTL(KC_BSPC), LCTL(KC_W), WRITE, KC_TRNS, LCTL(KC_A), KC_TRNS, KC_PGDN, KC_LEFT, KC_DOWN, KC_RGHT, KC_TRNS, KC_TRNS,
            KC_AGIN, LCTL(KC_Z), LCTL(KC_X), LCTL(KC_C), LCTL(KC_V), KC_TRNS, KC_TRNS, LCTL(KC_LEFT), KC_CAPS, LCTL(KC_RGHT), KC_TRNS, KC_TRNS,
            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[3] = LAYOUT_ortho_5x12(
            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
            KC_TRNS, KC_TILD, KC_AT, KC_PERC, KC_EXLM, KC_GRV, KC_AMPR, KC_7, KC_8, KC_9, KC_BSLS, KC_PIPE,
            LT(4,KC_BSPC), KC_PLUS, KC_CIRC, KC_COLN, KC_DLR, KC_HASH, KC_ASTR, KC_4, KC_5, KC_6, KC_MINS, ASSIGN,
            KC_TRNS, KC_DQUO, KC_COMM, KC_J, KC_K, KC_LT, KC_GT, KC_1, KC_2, KC_3, KC_QUES, KC_DOT,
            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_SPC, KC_0, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[4] = LAYOUT_ortho_5x12(
            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
            KC_TRNS, LSFT(KC_Q), LSFT(KC_Y), LSFT(KC_O), LSFT(KC_U), LSFT(KC_Z), LSFT(KC_W), LSFT(KC_D), LSFT(KC_N), LSFT(KC_C), LSFT(KC_B),
            KC_TRNS, KC_TRNS, LSFT(KC_H), LSFT(KC_I), LSFT(KC_E), LSFT(KC_A), KC_TRNS, LSFT_T(KC_G), LSFT(KC_T), LSFT(KC_R), LSFT(KC_S),
            LSFT(KC_P), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, LSFT(KC_J), LSFT(KC_K), LSFT(KC_X), LSFT(KC_V), LSFT(KC_M), LSFT(KC_L),
            LSFT(KC_F), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[5] = LAYOUT_ortho_5x12(
            RESET, LSFT(KC_F4), LSFT(KC_F5), LSFT(KC_F6), LSFT(KC_F7), LSFT(KC_F8), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
            KC_TRNS, KC_F12, KC_F7, KC_F8, KC_F9, LSFT(KC_F3), KC_TRNS, KC_HOME, KC_UP, KC_END, KC_TRNS, KC_TRNS,
            KC_TRNS, KC_F11, KC_F4, KC_F5, KC_F6, LSFT(KC_F2), KC_PGDN, KC_LEFT, KC_DOWN, KC_RGHT, KC_TRNS, KC_TRNS,
            KC_TRNS, KC_F10, KC_F1, KC_F2, KC_F3, LSFT(KC_F1), KC_TRNS, LCTL(KC_LEFT), KC_CAPS, LCTL(KC_RGHT), KC_TRNS, KC_TRNS,
            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[6] = LAYOUT_ortho_5x12(
            KC_ESC,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_BSPC,
            KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_DEL,
            KC_LSFT, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,
            KC_LCTL, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_ENT,
            KC_LGUI, KC_LCTL, KC_LALT, KC_LALT, KC_SPC,  KC_SPC,  KC_SPC,  KC_TRNS, KC_LEFT, KC_DOWN, KC_UP,   TG(6)),
};
